### ISSUE TITLE
：）

### ISSUE THREAD

**Issue by MengY0620** [lxy764139720/IrisRecognition#1]
学长您好，我目前正在研究虹膜识别的相关问题，在找到了您写的代码后，我把它搬到了树莓派上之后，出现了一些奇怪的问题一直在困扰我，实在无法解决。。我十分期待学长的指点！谢谢(*°∀°)=3！

**Comment by lxysl** [comment]
您好，可以把报错信息贴出来看下。

**Comment by MengY0620** [comment]
> 您好，可以把报错信息贴出来看下。
您好，不知道为什么上传不了图片，只能先把报错复制粘贴到这上边...我用摄像头拍了一组照片，命名为6（之前您有5组），在树莓派上用jupyterlab运行了第四段代码，之后他出现了如下这一段报错。程序依然在feature文件夹里面生成了/6/R的bmp文件，但没有/6/L的bmp文件...
AttributeError                            Traceback (most recent call last)AttributeError: 'NoneType' object has no attribute 'rint'The above exception was the direct cause of the following exception:TypeError                                 Traceback (most recent call last)/tmp/ipykernel_2750/177640281.py in <module>      4 fdp = r'./feature'      5 ----> 6 generateFeatureDataset(feature_dataset_path=fdp, dataset_path=dp, mode='swt')      7 print('已完成')~/iris_recognition/util/feature.py in generateFeatureDataset(feature_dataset_path, dataset_path, mode)     29             img_path = os.path.join(path, file_name)     30             save_path = feature_dataset_path + img_path[len(dataset_path):-len(file_name.split('.')[-1])] + 'bmp'---> 31             feature = getFeatureMap(cv2.imread(img_path, 0), mode)     32             cv2.imwrite(save_path, feature)     33             i += 1~/iris_recognition/util/feature.py in getFeatureMap(img, mode)     36 def getFeatureMap(img, mode='swt'):     37     # 提取每张照片的特征---> 38     inner = innerCircle(img)     39     outer = outerCircle(img, inner)     40     polar_array, polar_noise = normalize(img, outer[0], outer[1], outer[2], inner[0], inner[1], inner[2], height, width)~/iris_recognition/util/innerCircle.py in innerCircle(img)     22     circles = cv2.HoughCircles(img, cv2.HOUGH_GRADIENT, 2, 5,     23                                param1=110, param2=20, minRadius=20, maxRadius=130)---> 24     circles = np.int16(np.around(circles))     25     circles[0, :, 2] += 3     26 <__array_function__ internals> in around(*args, **kwargs)/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py in around(a, decimals, out)   3291    3292     """-> 3293     return _wrapfunc(a, 'round', decimals=decimals, out=out)   3294    3295 /usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)     53     bound = getattr(obj, method, None)     54     if bound is None:---> 55         return _wrapit(obj, method, *args, **kwds)     56      57     try:/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py in _wrapit(obj, method, *args, **kwds)     42     except AttributeError:     43         wrap = None---> 44     result = getattr(asarray(obj), method)(*args, **kwds)     45     if wrap:     46         if not isinstance(result, mu.ndarray):TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable rint method

**Comment by MengY0620** [comment]
> > 您好，可以把报错信息贴出来看下。
> 您好，不知道为什么上传不了图片，只能先把报错复制粘贴到这上边...我用摄像头拍了一组照片，命名为6（之前您有5组），在树莓派上用jupyterlab运行了第四段代码，之后他出现了如下这一段报错。程序依然在feature文件夹里面生成了/6/R的bmp文件，但没有/6/L的bmp文件...
> AttributeError                            Traceback (most recent call last)AttributeError: 'NoneType' object has no attribute 'rint'The above exception was the direct cause of the following exception:TypeError                                 Traceback (most recent call last)/tmp/ipykernel_2750/177640281.py in <module>      4 fdp = r'./feature'      5 ----> 6 generateFeatureDataset(feature_dataset_path=fdp, dataset_path=dp, mode='swt')      7 print('已完成')~/iris_recognition/util/feature.py in generateFeatureDataset(feature_dataset_path, dataset_path, mode)     29             img_path = os.path.join(path, file_name)     30             save_path = feature_dataset_path + img_path[len(dataset_path):-len(file_name.split('.')[-1])] + 'bmp'---> 31             feature = getFeatureMap(cv2.imread(img_path, 0), mode)     32             cv2.imwrite(save_path, feature)     33             i += 1~/iris_recognition/util/feature.py in getFeatureMap(img, mode)     36 def getFeatureMap(img, mode='swt'):     37     # 提取每张照片的特征---> 38     inner = innerCircle(img)     39     outer = outerCircle(img, inner)     40     polar_array, polar_noise = normalize(img, outer[0], outer[1], outer[2], inner[0], inner[1], inner[2], height, width)~/iris_recognition/util/innerCircle.py in innerCircle(img)     22     circles = cv2.HoughCircles(img, cv2.HOUGH_GRADIENT, 2, 5,     23                                param1=110, param2=20, minRadius=20, maxRadius=130)---> 24     circles = np.int16(np.around(circles))     25     circles[0, :, 2] += 3     26 <__array_function__ internals> in around(*args, **kwargs)/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py in around(a, decimals, out)   3291    3292     """-> 3293     return _wrapfunc(a, 'round', decimals=decimals, out=out)   3294    3295 /usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)     53     bound = getattr(obj, method, None)     54     if bound is None:---> 55         return _wrapit(obj, method, *args, **kwds)     56      57     try:/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py in _wrapit(obj, method, *args, **kwds)     42     except AttributeError:     43         wrap = None---> 44     result = getattr(asarray(obj), method)(*args, **kwds)     45     if wrap:     46         if not isinstance(result, mu.ndarray):TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable rint method
> 
可能有些乱，方便的话您可以添加一下我的QQ..

**Comment by lxysl** [comment]
报错信息显示在您的图片中没有检测到霍夫圆，您应该使用专用的虹膜采集摄像头进行拍摄。
https://stackoverflow.com/questions/60601374/hough-circle-detction-attributeerror-nonetype-object-has-no-attribute-rint

**Comment by MengY0620** [comment]
> 这可能是照片拍摄模糊的问题吗？。。？

**Comment by lxysl** [comment]
您可以把拍摄的图片上传看一下。
https://blog.csdn.net/qq_19934363/article/details/101481444

**Comment by MengY0620** [comment]
![QQ图片20211024195303](https://user-images.githubusercontent.com/93063164/138592891-76204d9f-58d8-465a-82c0-3f89e9a18012.png)
![QQ图片20211024195310](https://user-images.githubusercontent.com/93063164/138592892-6c0a1a0a-3099-4b48-8687-dd45661c0815.png)
![QQ图片20211024195316](https://user-images.githubusercontent.com/93063164/138592893-9a2aefb0-b5fb-44fc-acf2-3812833c9a46.png)
这个是我拍摄的左眼，下面的是我采用的摄像头：
![1635076533399](https://user-images.githubusercontent.com/93063164/138592972-12ac34a9-d151-4c49-bd97-a2a3188e7c1f.jpg)
![1635076538403](https://user-images.githubusercontent.com/93063164/138592971-51a20ca3-9d19-4c30-8f72-68fcbdb4390a.jpg)

**Comment by lxysl** [comment]
您拍摄的虹膜太小了，我设置的霍夫圆检测参数有最小半径限制，请您参考/photo下的图片进行拍摄。本代码可以在检测界面绘制出绿色的虹膜内外圆标志（readme中的图片），请以实时画面中检测出内外圆的图片为准。

**Comment by MengY0620** [comment]
> 您可以把拍摄的图片上传看一下。
> https://blog.csdn.net/qq_19934363/article/details/101481444

嗯嗯，我再拍摄一组试一下😄

**Comment by MengY0620** [comment]
> 您拍摄的虹膜太小了，我设置的霍夫圆检测参数有最小半径限制，请您参考/photo下的图片进行拍摄。本代码可以在检测界面绘制出绿色的虹膜内外圆标志（readme中的图片），请以实时画面中检测出内外圆的图片为准。

还有一个问题，您有什么推荐的虹膜摄像头吗？我目前使用的只可以拍摄黑白照片，晚上无法拍摄😞

**Comment by lxysl** [comment]
readme：选用焦距5.0mm可视角度65°的USB红外摄像头（手动旋转镜头调焦），以及12V红外LED补光灯。

**Comment by MengY0620** [comment]
> readme：选用焦距5.0mm可视角度65°的USB红外摄像头（手动旋转镜头调焦），以及12V红外LED补光灯。

谢谢您！问题完美的解决了！
