### ISSUE TITLE
大佬项目不用机器学习识别准确率高吗？

### ISSUE THREAD

**Issue by LMaxxxx** [lxy764139720/IrisRecognition#2]

**Comment by lxysl** [comment]
距离度量或者相似度度量也是广义上的机器学习。准确率只能说还行，想进一步提高可以考虑用度量学习或者对比学习训练一下，例如 cosface, arcface 等。

**Comment by LMaxxxx** [comment]
还有一个问题，虹膜采集那个相机有型号吗？我找到的都好贵，普通相机拍不到虹膜，十分感谢大佬！

**Comment by lxysl** [comment]
https://github.com/lxysl/IrisRecognition/issues/1#issuecomment-950319705 按这个搜一下？
